#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : uk                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://elplugins.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/elplugins.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ElPlugins                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : $15                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Full and Semi-Automatic OSRS Plugins

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : ElPlugins                           
your_link                                 : https://elplugins.com                
your_city                                 : Gielinor                            
email_address                             : elliott@elplugins.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : elli-tt
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : RuneLite
    description                           : Runs on a custom loader for RuneLite called RLPL.
    fontawesome_icon_name                 : magic
    
  - title                                 : Multiple Modes
    description                           : The plugins have a FULL AUTO and a SMART CLICK (Manual) mode.
    fontawesome_icon_name                 : mobile

  - title                                 : Jagex Launcher
    description                           : Client supports all Username, Email and JL logins.
    fontawesome_icon_name                 : play-circle

  - title                                 : Frequent Updates
    description                           : Plugins are updated frequently.
    fontawesome_icon_name                 : sync

  - title                                 : Minimal Downtime
    description                           : The client is updated shortly after the official RuneLite update for minimal downtime.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Supporting all your Combat, Skilling, Minigame, Utility and PVM needs.
    fontawesome_icon_name                 : star

  - title                                 : Fully Customisable
    description                           : Delays and settings are fully customisable between plugins.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Support
    description                           : All of our support channels are listed on our Discord server. They become unlocked after purchase.
    fontawesome_icon_name                 : link

  - title                                 : Frequently Asked Questions
    description                           : This section is available on our Discord server!
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
